<section id="nav" class="w-100 position-relative">
    <button id="admin_nav" class="btn btn-secondary w-100 pt-2 pb-2 text-center dropdown-toggle" data-toggle="dropdown">Menu</button>
    <div aria-labelled="admin_nav" class="dropdown-menu w-100">
        <a href="<?=$this->getURLSlash(1)?>/vip" class="dropdown-item">VIP aktivace</a>
        <a href="<?=$this->getURLSlash(1)?>/groups" class="dropdown-item">Přidělení skupiny</a>
    </div>
</section>