<article>
    <?=User::isModerator([1,2]) ? '<form action="#" method="POST">': ''?>
    <?php
        $details = $this->getDetail()[0];
    ?>
    <table class="table table-striped table-dark">
        <tbody>
            <tr>
                <td>Nick</td>
                <td><?=$details['name']?> - <a href="https://lexten.cz/stats/<?=User::toCommunityId($details['steamid'])?>">Zobrazit profil</a></td>
            </tr> 
            <tr>
                <td>Identifikační údaje</td>
                <td><?=$details['steamid']?> / <?=$details['accountid']?></td>
            </tr>
            <tr>
                <td>Zabanovaný dne</td>
                <td><?=date("d.m.Y H:i", isset($details['added']) ? $details['added'] : $details['time'])?></td>
            </tr>
            <tr>
                <td>Stav banu</td>
                <td><?=isset($details['rounds_actual']) ? (User::isModerator([1,2]) ? '<input type="number" name="rounds_actual" placeholder="Zbývá kol" value="'.$details['rounds_actual'].'"/> / <input type="number" name="rounds_given" placeholder="Počet kol" value="'.$details['rounds_given'].'"/> kol' : $details['rounds_actual'].' / '.$details['rounds_given'].' kol') : (User::isModerator([1,2]) ? '<input type="datetime-local" name="expire" value="'.date("Y-m-d\TH:i:s", $details['expire']).'" />' : 'Vyprší '.date("d.m.Y H:i", $details['expire'])) ?></td>
            </tr>
            <tr>
                <td>Admin</td>
                <td><?=$details['admin_name']?> - <a href="https://lexten.cz/stats/<?=User::toCommunityId($details['admin_steamid'])?>">Zobrazit profil</a></td>
            </tr>
            <tr>
                <td>Důvod</td>
                <td><?=User::isModerator([1,2]) ? '<input type="text" name="reason" placeholder="Důvod" value="'.$details["reason"].'" />' : $details['reason']?></td>
            </tr>
        </tbody>
    </table>
    <?=User::isModerator([1,2]) ? '<button name="edit" class="btn btn-secondary w-100 mb-2">Upravit ban</button><button name="delete" class="btn btn-danger w-100">Smazat ban</button></form>': ''?>
</article>