<article class="halfpage">
<?php
    $sections = $this->getSection();
    for($i = 0; $i < count($sections); $i++){
        if($sections[$i]['typ'] == 0){
        ?>
            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th><?=$sections[$i]['nazev']?></th>
                        <th>Statistiky</th>
                        <th>Poslední komentář</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        for($j = 0; $j < count($sections); $j++){
                            if($sections[$j]['podrazeno'] == $sections[$i]['id'] && $sections[$j]['typ'] == 1){
                                ?>
                                    <tr>
                                        <td><img src="<?=$sections[$j]['icon-img']?>" width="30px" alt="Sekce obrázek"/> <a href="/forum/sekce/<?=$sections[$j]['id']?>"><?=$sections[$j]['nazev']?></a></td>
                                        <td><?php
                                            echo $sections[$j]['topics'].' témat<br/>'.$sections[$j]['replies'].' odpovědí';
                                            ?></td>
                                        <td><?php
                                            $lastcomment = $this->getLastComment($section = $sections[$j]['id']);
                                            echo '<img src="'.$lastcomment['avatarsmall'].'" class="avatar" alt="Avatar" /> ';
                                            echo '<a href="/stats/'.$lastcomment['author'].'" '.(!empty($lastcomment['barva']) ? 'style="color: #'.$lastcomment['barva'].'"' : '').'>'.$lastcomment['nick'].'</a><br/><a href="/forum/topic/'.($lastcomment['podrazeno'] == 0 ? $lastcomment['id'] : $lastcomment['podrazeno']).'">'.date("d. m. Y H:i", strtotime($lastcomment['datum'])).'</a>';
                                        ?></td>
                                    </tr>
                                <?php
                            }
                        }
                    ?>
                </tbody>
            </table>
        <?php
        }
    }
?>
</article>
<?php
require('aside.phtml');
?>